// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Server/DataServer.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace DataServer {
  public static partial class DataServer
  {
    static readonly string __ServiceName = "DataServer.DataServer";

    static readonly grpc::Marshaller<global::DataServer.Input> __Marshaller_DataServer_Input = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DataServer.Input.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DataServer.Output> __Marshaller_DataServer_Output = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DataServer.Output.Parser.ParseFrom);

    static readonly grpc::Method<global::DataServer.Input, global::DataServer.Output> __Method_Send = new grpc::Method<global::DataServer.Input, global::DataServer.Output>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Send",
        __Marshaller_DataServer_Input,
        __Marshaller_DataServer_Output);

    static readonly grpc::Method<global::DataServer.Input, global::DataServer.Output> __Method_CallBack = new grpc::Method<global::DataServer.Input, global::DataServer.Output>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CallBack",
        __Marshaller_DataServer_Input,
        __Marshaller_DataServer_Output);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DataServer.DataServerReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DataServer</summary>
    [grpc::BindServiceMethod(typeof(DataServer), "BindService")]
    public abstract partial class DataServerBase
    {
      public virtual global::System.Threading.Tasks.Task<global::DataServer.Output> Send(global::DataServer.Input request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::DataServer.Output> CallBack(global::DataServer.Input request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DataServer</summary>
    public partial class DataServerClient : grpc::ClientBase<DataServerClient>
    {
      /// <summary>Creates a new client for DataServer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public DataServerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DataServer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public DataServerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected DataServerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected DataServerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::DataServer.Output Send(global::DataServer.Input request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Send(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DataServer.Output Send(global::DataServer.Input request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Send, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::DataServer.Output> SendAsync(global::DataServer.Input request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::DataServer.Output> SendAsync(global::DataServer.Input request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Send, null, options, request);
      }
      public virtual global::DataServer.Output CallBack(global::DataServer.Input request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CallBack(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DataServer.Output CallBack(global::DataServer.Input request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CallBack, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::DataServer.Output> CallBackAsync(global::DataServer.Input request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CallBackAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::DataServer.Output> CallBackAsync(global::DataServer.Input request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CallBack, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override DataServerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DataServerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(DataServerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Send, serviceImpl.Send)
          .AddMethod(__Method_CallBack, serviceImpl.CallBack).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DataServerBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Send, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DataServer.Input, global::DataServer.Output>(serviceImpl.Send));
      serviceBinder.AddMethod(__Method_CallBack, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DataServer.Input, global::DataServer.Output>(serviceImpl.CallBack));
    }

  }
}
#endregion
